site_name: Unlock your Agents Potential with MCP
site_author: Dave Glover
site_description: >-
  Azure AI Foundry Agent Services with MCP Workshop.

# Repository ..................................................
repo_name: Unlock your Agents Potential with MCP
repo_url: https://github.com/microsoft/aitour26-WRK540-unlock-your-agents-potential-with-model-context-protocol

# Copyright ...................................................
copyright: >
  Copyright &copy; 2023 - present Microsoft

nav:
  - Workshop Introduction: index.md
  - Workshop Navigation: navigating-the-workshop.md
  - Getting Started:
      - Open the Workshop: getting-started.md
      - Architecture Overview: architecture.md
  - Agent Services Labs:
      - AI Foundry Agent Services: agent-service-overview.md
      - Lab 1 Agent Instructions: lab-1-agent-instructions.md
      - Lab 2 Start your Agent: lab-2-start-the-agent.md
      - Lab 3 Semantic Search: lab-3-mcp-semantic-search.md
      - Lab 4 Securing Agent Data: lab-4-secure-agent-data.md
  - Observability Labs:
      - Observability Overview: observability-overview.md
      - Lab 5 Service Monitoring: lab-5-monitoring.md
      - Lab 6 Understand Tracing: lab-6-tracing.md

  - Star and Connect: star-and-connect.md
  - Finishing Up: lab-7-finishing-up.md
  - Summary: summary.md
  - Resources: resources.md
  - Bonus content:
      - Local Tracing with Aspire: lab-7-local-tracing-with-aspire.md
  - About: about.md

plugins:
  - search
  - glightbox
  - include-markdown
  # - timetoread:
  #     wpm: 180
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          site_name: Unlock your Agents Potential with MCP
          admonition_translations:
            tip: tip
            warning: Warning
            info: Information
            note: Note
            danger: Danger
            success: Success
            question: Question
          nav_translations:
            Workshop Introduction: Workshop Introduction
            Workshop Navigation: Workshop Navigation
            Getting Started: Getting Started
            Architecture Overview: Architecture Overview
            Agent Services Labs: Agent Services Labs
            AI Foundry Agent Services: AI Foundry Agent Services
            Lab 1 Agent Instructions: Lab 1 Agent Instructions
            Lab 2 Start your Agent: Lab 2 Start your Agent
            Lab 3 Semantic Search: Lab 3 Semantic Search
            Lab 4 Securing Agent Data: Lab 4 Securing Agent Data
            Observability Labs: Observability Labs
            Observability Overview: Observability Overview
            Lab 5 Service Monitoring: Lab 5 Service Monitoring
            Lab 6 Understand Tracing: Lab 6 Understand Tracing
            Star and Connect: Star and Connect
            Finishing Up: Finishing Up
            Summary: Summary
            Resources: Resources
            Bonus content: Bonus content
            Local Tracing with Aspire: Local Tracing with Aspire
            About: About
        - locale: fr
          name: Français
          site_name: Libérez le potentiel de vos agents avec MCP
          admonition_translations:
            tip: Conseil
            warning: Avertissement
            info: Information
            note: Remarque
            danger: Danger
            success: Succès
            question: Question
          nav_translations:
            Workshop Introduction: Introduction de l'atelier
            Workshop Navigation: Navigation de l'atelier
            Getting Started: Commencer
            Architecture Overview: Vue d'ensemble de l'architecture
            Agent Services Labs: Labs des services d'agents
            AI Foundry Agent Services: Services d'agents AI Foundry
            Lab 1 Agent Instructions: Lab 1 Instructions de l'agent
            Lab 2 Start your Agent: Lab 2 Démarrez votre agent
            Lab 3 Semantic Search: Lab 3 Recherche sémantique
            Lab 4 Securing Agent Data: Lab 4 Sécurisation des données de l'agent
            Observability Labs: Labs d'observabilité
            Observability Overview: Vue d'ensemble de l'observabilité
            Lab 5 Service Monitoring: Lab 5 Surveillance des services
            Lab 6 Understand Tracing: Lab 6 Comprendre le traçage
            Star and Connect: Étoile et connexion
            Finishing Up: Finalisation
            Summary: Résumé
            Resources: Ressources
            Bonus content: Contenu bonus
            Local Tracing with Aspire: Traçage local avec Aspire
            About: À propos

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
  # emoji_index: !!python/name:material.extensions.emoji.twemoji
  # emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css
