site_name: Unlock your Agents Potential with MCP
site_author: Dave Glover
site_description: >-
  Azure AI Foundry Agent Services with MCP Workshop.
site_url: https://microsoft.github.io/aitour26-WRK540-unlock-your-agents-potential-with-model-context-protocol/

# Repository ..................................................
repo_name: Unlock your Agents Potential with MCP
repo_url: https://github.com/microsoft/aitour26-WRK540-unlock-your-agents-potential-with-model-context-protocol

# Copyright ...................................................
copyright: >
  Copyright &copy; 2023 - present Microsoft

nav:
  - Workshop Introduction: index.md
  - Workshop Navigation: navigating-the-workshop.md
  - Getting Started:
      - Open the Workshop: getting-started.md
      - Architecture Overview: architecture.md
  - Agent Services Labs:
      - AI Foundry Agent Services: agent-service-overview.md
      - Lab 1 Agent Instructions: lab-1-agent-instructions.md
      - Lab 2 Start your Agent: lab-2-start-the-agent.md
      - Lab 3 Semantic Search: lab-3-mcp-semantic-search.md
      - Lab 4 Securing Agent Data: lab-4-secure-agent-data.md
  - Observability Labs:
      - Observability Overview: observability-overview.md
      - Lab 5 Service Monitoring: lab-5-monitoring.md
      - Lab 6 Understand Tracing: lab-6-tracing.md

  - Star and Connect: star-and-connect.md
  - Finishing Up: lab-7-finishing-up.md
  - Summary: summary.md
  - Resources: resources.md
  - Bonus content:
      - Local Tracing with Aspire: lab-7-local-tracing-with-aspire.md
  - About: about.md

plugins:
  - search
  - glightbox
  - include-markdown
  # - timetoread:
  #     wpm: 180
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          site_name: Unlock your Agents Potential with MCP
          admonition_translations:
            tip: tip
            warning: Warning
            info: Information
            note: Note
            danger: Danger
            success: Success
            question: Question
          nav_translations:
            Workshop Introduction: Workshop Introduction
            Workshop Navigation: Workshop Navigation
            Getting Started: Getting Started
            Open the Workshop: Open the Workshop
            Architecture Overview: Architecture Overview
            Agent Services Labs: Agent Services Labs
            AI Foundry Agent Services: AI Foundry Agent Services
            Lab 1 Agent Instructions: Lab 1 Agent Instructions
            Lab 2 Start your Agent: Lab 2 Start your Agent
            Lab 3 Semantic Search: Lab 3 Semantic Search
            Lab 4 Securing Agent Data: Lab 4 Securing Agent Data
            Observability Labs: Observability Labs
            Observability Overview: Observability Overview
            Lab 5 Service Monitoring: Lab 5 Service Monitoring
            Lab 6 Understand Tracing: Lab 6 Understand Tracing
            Star and Connect: Star and Connect
            Finishing Up: Finishing Up
            Summary: Summary
            Resources: Resources
            Bonus content: Bonus content
            Local Tracing with Aspire: Local Tracing with Aspire
            About: About
        - locale: fr
          name: Français
          site_name: Libérez le potentiel de vos agents avec MCP
          admonition_translations:
            tip: Conseil
            warning: Avertissement
            info: Information
            note: Remarque
            danger: Danger
            success: Succès
            question: Question
          nav_translations:
            Workshop Introduction: Introduction de l'atelier
            Workshop Navigation: Navigation de l'atelier
            Getting Started: Commencer
            Open the Workshop: Ouvrir l'atelier
            Architecture Overview: Vue d'ensemble de l'architecture
            Agent Services Labs: Labs des services d'agents
            AI Foundry Agent Services: Services d'agents AI Foundry
            Lab 1 Agent Instructions: Lab 1 Instructions de l'agent
            Lab 2 Start your Agent: Lab 2 Démarrez votre agent
            Lab 3 Semantic Search: Lab 3 Recherche sémantique
            Lab 4 Securing Agent Data: Lab 4 Sécurisation des données de l'agent
            Observability Labs: Labs d'observabilité
            Observability Overview: Vue d'ensemble de l'observabilité
            Lab 5 Service Monitoring: Lab 5 Surveillance des services
            Lab 6 Understand Tracing: Lab 6 Comprendre le traçage
            Star and Connect: Étoile et connexion
            Finishing Up: Finalisation
            Summary: Résumé
            Resources: Ressources
            Bonus content: Contenu bonus
            Local Tracing with Aspire: Traçage local avec Aspire
            About: À propos
        - locale: es
          name: Español
          site_name: Libera el Potencial de tus Agentes con MCP
          admonition_translations:
            tip: Consejo
            warning: Advertencia
            info: Información
            note: Nota
            danger: Peligro
            success: Éxito
            question: Pregunta
          nav_translations:
            Workshop Introduction: Introducción del Taller
            Workshop Navigation: Navegación del Taller
            Getting Started: Comenzando
            Open the Workshop: Abrir el Taller
            Architecture Overview: Visión General de la Arquitectura
            Agent Services Labs: Laboratorios de Servicios de Agentes
            AI Foundry Agent Services: Servicios de Agentes AI Foundry
            Lab 1 Agent Instructions: Lab 1 Instrucciones del Agente
            Lab 2 Start your Agent: Lab 2 Inicia tu Agente
            Lab 3 Semantic Search: Lab 3 Búsqueda Semántica
            Lab 4 Securing Agent Data: Lab 4 Asegurando Datos del Agente
            Observability Labs: Laboratorios de Observabilidad
            Observability Overview: Visión General de Observabilidad
            Lab 5 Service Monitoring: Lab 5 Monitoreo de Servicios
            Lab 6 Understand Tracing: Lab 6 Entender el Trazado
            Star and Connect: Dar Estrella y Conectar
            Finishing Up: Finalizando
            Summary: Resumen
            Resources: Recursos
            Bonus content: Contenido Adicional
            Local Tracing with Aspire: Trazado Local con Aspire
            About: Acerca de
        - locale: it
          name: Italiano
          site_name: Libera il Potenziale dei tuoi Agenti con MCP
          admonition_translations:
            tip: Suggerimento
            warning: Avvertimento
            info: Informazione
            note: Nota
            danger: Pericolo
            success: Successo
            question: Domanda
          nav_translations:
            Workshop Introduction: Introduzione al Workshop
            Workshop Navigation: Navigazione del Workshop
            Getting Started: Iniziamo
            Open the Workshop: Aprire il Workshop
            Architecture Overview: Panoramica dell'Architettura
            Agent Services Labs: Lab dei Servizi Agenti
            AI Foundry Agent Services: Servizi Agenti AI Foundry
            Lab 1 Agent Instructions: Lab 1 Istruzioni dell'Agente
            Lab 2 Start your Agent: Lab 2 Avvia il tuo Agente
            Lab 3 Semantic Search: Lab 3 Ricerca Semantica
            Lab 4 Securing Agent Data: Lab 4 Protezione Dati dell'Agente
            Observability Labs: Lab di Osservabilità
            Observability Overview: Panoramica dell'Osservabilità
            Lab 5 Service Monitoring: Lab 5 Monitoraggio dei Servizi
            Lab 6 Understand Tracing: Lab 6 Comprensione del Tracing
            Star and Connect: Star e Connessioni
            Finishing Up: Completamento
            Summary: Riassunto
            Resources: Risorse
            Bonus content: Contenuto Bonus
            Local Tracing with Aspire: Tracing Locale con Aspire
            About: Informazioni
        - locale: ja
          name: 日本語
          site_name: MCPでエージェントの可能性を解き放つ
          admonition_translations:
            tip: ヒント
            warning: 警告
            info: 情報
            note: 注意
            danger: 危険
            success: 成功
            question: 質問
          nav_translations:
            Workshop Introduction: ワークショップ紹介
            Workshop Navigation: ワークショップナビゲーション
            Getting Started: はじめに
            Open the Workshop: ワークショップを開く
            Architecture Overview: アーキテクチャ概要
            Agent Services Labs: エージェントサービスラボ
            AI Foundry Agent Services: AI Foundry エージェントサービス
            Lab 1 Agent Instructions: ラボ1 エージェント指示
            Lab 2 Start your Agent: ラボ2 エージェントの開始
            Lab 3 Semantic Search: ラボ3 セマンティック検索
            Lab 4 Securing Agent Data: ラボ4 エージェントデータの保護
            Observability Labs: 可観測性ラボ
            Observability Overview: 可観測性概要
            Lab 5 Service Monitoring: ラボ5 サービス監視
            Lab 6 Understand Tracing: ラボ6 トレーシングの理解
            Star and Connect: スターと接続
            Finishing Up: 完了
            Summary: まとめ
            Resources: リソース
            Bonus content: ボーナスコンテンツ
            Local Tracing with Aspire: Aspireでのローカルトレーシング
            About: について
        - locale: ko
          name: 한국어
          site_name: MCP로 에이전트의 잠재력 발휘하기
          admonition_translations:
            tip: 팁
            warning: 경고
            info: 정보
            note: 참고
            danger: 위험
            success: 성공
            question: 질문
          nav_translations:
            Workshop Introduction: 워크숍 소개
            Workshop Navigation: 워크숍 네비게이션
            Getting Started: 시작하기
            Open the Workshop: 워크숍 열기
            Architecture Overview: 아키텍처 개요
            Agent Services Labs: 에이전트 서비스 랩
            AI Foundry Agent Services: AI Foundry 에이전트 서비스
            Lab 1 Agent Instructions: 랩 1 에이전트 지시사항
            Lab 2 Start your Agent: 랩 2 에이전트 시작하기
            Lab 3 Semantic Search: 랩 3 의미적 검색
            Lab 4 Securing Agent Data: 랩 4 에이전트 데이터 보안
            Observability Labs: 가관측성 랩
            Observability Overview: 가관측성 개요
            Lab 5 Service Monitoring: 랩 5 서비스 모니터링
            Lab 6 Understand Tracing: 랩 6 추적 이해하기
            Star and Connect: 별표와 연결
            Finishing Up: 마무리
            Summary: 요약
            Resources: 리소스
            Bonus content: 보너스 콘텐츠
            Local Tracing with Aspire: Aspire를 사용한 로컬 추적
            About: 정보
        - locale: zh
          name: 中文
          site_name: 使用 MCP 释放代理的潜力
          admonition_translations:
            tip: 提示
            warning: 警告
            info: 信息
            note: 注意
            danger: 危险
            success: 成功
            question: 问题
          nav_translations:
            Workshop Introduction: 工作坊介绍
            Workshop Navigation: 工作坊导航
            Getting Started: 开始
            Open the Workshop: 打开工作坊
            Architecture Overview: 架构概述
            Agent Services Labs: 代理服务实验
            AI Foundry Agent Services: AI Foundry 代理服务
            Lab 1 Agent Instructions: 实验 1 代理指令
            Lab 2 Start your Agent: 实验 2 启动您的代理
            Lab 3 Semantic Search: 实验 3 语义搜索
            Lab 4 Securing Agent Data: 实验 4 保护代理数据
            Observability Labs: 可观测性实验
            Observability Overview: 可观测性概述
            Lab 5 Service Monitoring: 实验 5 服务监控
            Lab 6 Understand Tracing: 实验 6 理解追踪
            Star and Connect: 加星标和连接
            Finishing Up: 完成
            Summary: 总结
            Resources: 资源
            Bonus content: 额外内容
            Local Tracing with Aspire: 使用 Aspire 进行本地追踪
            About: 关于

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
  # emoji_index: !!python/name:material.extensions.emoji.twemoji
  # emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css
